"""
keyword_spotting/training/synth_data.py
=========================================
Bootstrap synthetic dataset generator for the "NOVA" wake word.

Talks to Windows SAPI directly via win32com.client (SAPI.SpVoice /
SAPI.SpFileStream) to synthesize positive ("NOVA") and negative (other
words/phrases) audio, then applies light augmentation (pitch shift,
time stretch, gain, noise) to multiply the small set of synthetic base
recordings into a larger, more varied training set. Also generates a
handful of pure silence/background-noise negative clips.

NOTE ON IMPLEMENTATION: pyttsx3 was tried first and measured as
pathologically slow/unreliable on this machine when its engine is
reused across many synth calls in a loop (multiple seconds, sometimes
apparently hanging, per single short utterance). Talking to
SAPI.SpVoice/SpFileStream directly was measured at ~3-50ms per
utterance instead, so this script uses that path. This makes the
script Windows-specific (SAPI is a Windows API).

LIMITATIONS (read before trusting any accuracy number produced from
this data alone)
-----------------------------------------------------------------
- Only as many distinct voices as are installed via Windows SAPI on
  this machine (commonly 1-3). This is NOT real multi-speaker
  diversity.
- Synthetic TTS speech has a different acoustic character than real
  human speech; a model trained ONLY on this data will generalise
  poorly to a real microphone / real speaker.
- This script is a BOOTSTRAP step only. Combine it with
  keyword_spotting/training/record_data.py (real recordings from an
  actual speaker) before trusting any live-microphone accuracy claim.

Filenames are written as "{tag}_grp{N}_var{M}.wav": all variants
sharing one {N} are augmented copies of the same base utterance, and
keyword_spotting.training.splitting.derive_group_key() uses this to
keep them together in a single train/val/test split. NOTE: data
generated by an older version of this script (flat "{tag}_{count}.wav"
names) does not carry this grouping -- regenerate it to get real
leakage protection for those files.

Usage
-----
    python -m keyword_spotting.training.synth_data --out-dir data/kws/synthetic
"""

from __future__ import annotations

import argparse
import json
import tempfile
import time
from pathlib import Path
from typing import List

import numpy as np
import soundfile as sf

from audio_processing.utils import ensure_mono, normalize_audio, resample_if_needed
from keyword_spotting.features import DEFAULT_SAMPLE_RATE

# Derived from features.py (not a separate literal), so synthetic data can
# never silently drift from the sample rate training/inference actually use.
TARGET_SR = DEFAULT_SAMPLE_RATE

# SAPI SpVoice.Rate ranges -10 (slowest) .. 10 (fastest); 0 is normal speed.
SAPI_RATES = [-2, 0, 2]

POSITIVE_PHRASES = ["NOVA", "Nova", "nova", "Hey Nova", "Nova Nova"]

NEGATIVE_WORDS = [
    "hello", "computer", "assistant", "weather", "music", "light",
    "kitchen", "window", "morning", "please", "thank you", "goodbye",
    "yesterday", "tomorrow", "coffee", "table", "picture", "elephant",
    "umbrella", "notebook",
]

N_SILENCE_CLIPS = 20
N_NOISE_CLIPS = 20
CLIP_SECONDS = 1.2

SSFM_CREATE_FOR_WRITE = 3


def _load_and_resample(path: Path) -> np.ndarray:
    y, sr = sf.read(str(path))
    y = ensure_mono(y).astype(np.float32)
    if sr != TARGET_SR:
        y = resample_if_needed(y, sr, TARGET_SR)
    return normalize_audio(y)


def _augment(y: np.ndarray, sr: int, rng: np.random.Generator, heavy: bool) -> List[np.ndarray]:
    """Return y plus a handful of augmented variants, all still recognisable as the same utterance."""
    import librosa

    variants = [y]
    pitch_steps = (-2, 2) if heavy else (2,)
    for n_steps in pitch_steps:
        try:
            variants.append(librosa.effects.pitch_shift(y, sr=sr, n_steps=n_steps))
        except Exception:
            pass
    if heavy:
        for rate in (0.9, 1.1):
            try:
                variants.append(librosa.effects.time_stretch(y, rate=rate))
            except Exception:
                pass
        variants.append(np.clip(y * float(rng.uniform(0.7, 1.3)), -1.0, 1.0))
    noisy = y + rng.normal(0, 0.005, size=y.shape).astype(np.float32)
    variants.append(np.clip(noisy, -1.0, 1.0))
    return [normalize_audio(v.astype(np.float32)) for v in variants]


def _make_silence_and_noise_clips(neg_dir: Path, rng: np.random.Generator, start_count: int) -> int:
    """A few pure-silence and colored-noise negative clips (no speech at all)."""
    count = start_count
    n_samples = int(TARGET_SR * CLIP_SECONDS)

    for _ in range(N_SILENCE_CLIPS):
        # Near-silence with a tiny bit of noise floor, like a quiet room via a real mic.
        clip = (rng.normal(0, 0.001, size=n_samples)).astype(np.float32)
        sf.write(str(neg_dir / f"neg_{count:04d}.wav"), clip, TARGET_SR, subtype="PCM_16")
        count += 1

    for _ in range(N_NOISE_CLIPS):
        white = rng.normal(0, 1.0, size=n_samples).astype(np.float32)
        # Cheap pink-ish shaping: cumulative sum + normalize, to avoid pure-white-only noise.
        pink = np.cumsum(white)
        pink = pink / (np.max(np.abs(pink)) + 1e-8)
        gain = float(rng.uniform(0.02, 0.2))
        clip = (pink * gain).astype(np.float32)
        sf.write(str(neg_dir / f"neg_{count:04d}.wav"), clip, TARGET_SR, subtype="PCM_16")
        count += 1

    return count


def generate(out_dir: Path, seed: int = 0) -> dict:
    import win32com.client as wc

    rng = np.random.default_rng(seed)
    speaker = wc.Dispatch("SAPI.SpVoice")
    voices = list(speaker.GetVoices())
    if not voices:
        raise RuntimeError("No SAPI voices found on this system.")

    pos_dir = out_dir / "positive"
    neg_dir = out_dir / "negative"
    pos_dir.mkdir(parents=True, exist_ok=True)
    neg_dir.mkdir(parents=True, exist_ok=True)

    voice_names = [str(v.GetDescription()) for v in voices]

    def _run(words: List[str], target_dir: Path, tag: str, heavy: bool) -> int:
        count = 0
        group = 0  # one group per (voice, rate, word) base utterance
        with tempfile.TemporaryDirectory() as tmp:
            raw_path = Path(tmp) / "raw.wav"
            for voice in voices:
                speaker.Voice = voice
                for rate in SAPI_RATES:
                    speaker.Rate = rate
                    for word in words:
                        stream = wc.Dispatch("SAPI.SpFileStream")
                        stream.Open(str(raw_path), SSFM_CREATE_FOR_WRITE, False)
                        speaker.AudioOutputStream = stream
                        speaker.Speak(word)
                        stream.Close()
                        if not raw_path.exists():
                            continue
                        base = _load_and_resample(raw_path)
                        variants = _augment(base, TARGET_SR, rng, heavy=heavy)
                        # Filename encodes (group, variant) so
                        # keyword_spotting.training.splitting can keep every
                        # augmented variant of this base utterance together
                        # in the same train/val/test split.
                        for variant_idx, variant in enumerate(variants):
                            out_path = target_dir / f"{tag}_grp{group:04d}_var{variant_idx:02d}.wav"
                            sf.write(str(out_path), variant, TARGET_SR, subtype="PCM_16")
                            count += 1
                        group += 1
        return count

    t0 = time.perf_counter()
    n_pos = _run(POSITIVE_PHRASES, pos_dir, "pos", heavy=True)
    n_neg_speech = _run(NEGATIVE_WORDS, neg_dir, "neg", heavy=False)
    n_neg_total = _make_silence_and_noise_clips(neg_dir, rng, start_count=n_neg_speech)
    elapsed = time.perf_counter() - t0

    def _total_duration(folder: Path) -> float:
        total = 0.0
        for wav in folder.glob("*.wav"):
            info = sf.info(str(wav))
            total += info.frames / info.samplerate
        return total

    pos_duration = _total_duration(pos_dir)
    neg_duration = _total_duration(neg_dir)

    metadata = {
        "type": "synthetic",
        "target_sample_rate": TARGET_SR,
        "tts_backend": "Windows SAPI (win32com.client)",
        "voices_used": voice_names,
        "sapi_rates": SAPI_RATES,
        "positive_phrases": POSITIVE_PHRASES,
        "negative_words": NEGATIVE_WORDS,
        "n_silence_clips": N_SILENCE_CLIPS,
        "n_noise_clips": N_NOISE_CLIPS,
        "n_positive": n_pos,
        "n_negative_speech": n_neg_speech,
        "n_negative_total": n_neg_total,
        "positive_duration_s": round(pos_duration, 2),
        "negative_duration_s": round(neg_duration, 2),
        "generation_time_s": round(elapsed, 2),
        "seed": seed,
    }
    with open(out_dir / "metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"Synthetic positives written: {n_pos} -> {pos_dir}  ({pos_duration:.1f}s total)")
    print(f"Synthetic negatives written: {n_neg_total} -> {neg_dir}  ({neg_duration:.1f}s total)")
    print(f"  (of which {n_neg_speech} are speech, {n_neg_total - n_neg_speech} are silence/noise)")
    print(f"Generation time: {elapsed:.1f}s")
    print(f"Metadata written to {out_dir / 'metadata.json'}")
    print()
    print(
        "LIMITATION: this is synthetic TTS data from "
        f"{len(voice_names)} voice(s) ({', '.join(voice_names)}). Combine with "
        "keyword_spotting/training/record_data.py for real-speaker data "
        "before trusting live-microphone accuracy."
    )
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=str, default="data/kws/synthetic")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    generate(Path(args.out_dir), seed=args.seed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
