"""
api.routers.live
===================
LIVE-mode event feed for the NOVA smart-room frontend (frontend/code.html).

    GET  /live/state   - one-shot snapshot (device state + static model info)
    WS   /live/ws       - push channel for status / voice_result /
                          device_update / telemetry events, generated by
                          api.live_session's background pipeline thread

This router does not run any pipeline stage itself -- it only broadcasts
events that api.live_session.LiveVoiceSession already produced by driving
the existing, UNMODIFIED voice_pipeline.orchestrator.VoiceCommandOrchestrator.

DEMO mode is intentionally NOT served through this router at all: it runs
entirely client-side in frontend/code.html (see that file's DEMO_MODE
handling), so the demo stays usable even if this backend/WebSocket is
unavailable -- exactly the "must not crash if the backend isn't running"
requirement this integration was built to satisfy.
"""

from __future__ import annotations

import asyncio
import logging
from pathlib import Path
from typing import Any, Dict, Set

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from api.device_state import get_state
from api.live_session import get_live_session

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/live", tags=["live"])

_CHECKPOINT_PATH = Path("models/kws_nova_cnn.pt")

_connections: Set[WebSocket] = set()
_broadcast_task: "asyncio.Task | None" = None


def _model_footprint_kb() -> "float | None":
    try:
        return round(_CHECKPOINT_PATH.stat().st_size / 1024.0, 1)
    except OSError:
        return None


@router.get("/state")
async def live_state() -> Dict[str, Any]:
    """One-shot snapshot so a freshly loaded page isn't blank before the
    WebSocket connects (or if it never connects, e.g. WS blocked)."""
    session = get_live_session()
    return {
        "device_state": get_state(),
        "pipeline_status": session.status,
        "offline_reason": session.offline_reason,
        "kws_model": "TinyKWSNet",
        "keyword": "NOVA",
        "model_footprint_kb": _model_footprint_kb(),
    }


async def _broadcast_loop() -> None:
    """Drains api.live_session's thread-safe event queue (blocking, so run
    via an executor) and fans each event out to every connected client."""
    session = get_live_session()
    loop = asyncio.get_event_loop()
    while True:
        event = await loop.run_in_executor(None, session.events.get)
        dead: Set[WebSocket] = set()
        for ws in list(_connections):
            try:
                await ws.send_json(event)
            except Exception:
                dead.add(ws)
        _connections.difference_update(dead)


def start_broadcast_loop() -> None:
    """Call once at FastAPI startup."""
    global _broadcast_task
    if _broadcast_task is None:
        _broadcast_task = asyncio.ensure_future(_broadcast_loop())


def stop_broadcast_loop() -> None:
    global _broadcast_task
    if _broadcast_task is not None:
        _broadcast_task.cancel()
        _broadcast_task = None


@router.websocket("/ws")
async def live_ws(websocket: WebSocket) -> None:
    await websocket.accept()
    _connections.add(websocket)
    try:
        session = get_live_session()
        await websocket.send_json({
            "type": "snapshot",
            "device_state": get_state(),
            "pipeline_status": session.status,
            "offline_reason": session.offline_reason,
        })
        while True:
            # Client sends nothing meaningful today; this just detects
            # disconnects promptly instead of relying on a failed send().
            await websocket.receive_text()
    except WebSocketDisconnect:
        pass
    except Exception as exc:
        logger.info("live_ws connection closed: %s", exc)
    finally:
        _connections.discard(websocket)
